FROM node:alpine as BUILDER
WORKDIR /usr/src/app
COPY ethereum-dispatcher ethereum-dispatcher
WORKDIR /usr/src/app/ethereum-dispatcher
RUN yarn
RUN yarn build

FROM node:alpine 
WORKDIR /usr/src/app/ethereum-dispatcher
COPY --from=BUILDER /usr/src/app/ethereum-dispatcher/lib lib
COPY --from=BUILDER /usr/src/app/ethereum-dispatcher/package.json .
COPY --from=BUILDER /usr/src/app/ethereum-dispatcher/node_modules node_modules

ARG PORT
EXPOSE $PORT
ENTRYPOINT yarn start
