version: "3.9"
services:
  ethereum-dispatcher:
    volumes:
      - vscode-exts:/root/.vscode-server/extensions
      - vscode-exts-insiders:/root/.vscode-server-insiders/extensions
      - ~/.config/gh:/root/.config/gh
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - ethereum-dispatcher
    depends_on:
      - kafka

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOIPCS: "ethereum-block-number:1:1,ethereum-block-content:1:1"
      KAFKA_LOG_DIRS: /logs
    depends_on:
      - zookeeper
    networks:
      - ethereum-dispatcher
    volumes:
      - kafka-logs:/logs

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      - ethereum-dispatcher
    environment:
      - ZK_DATADIR:/zookeeper-data
    volumes:
      - zookeeper-datadir:/zookeeper-data

volumes:
  vscode-exts:
  vscode-exts-insiders:
  kafka-logs:
  zookeeper-datadir:

networks:
  ethereum-dispatcher:
